#!/bin/sh
python3 Scripts/predict.py m1_7 201 65 
python3 Scripts/predict.py m1_7 202 80 
python3 Scripts/predict.py m1_7 208 70 
python3 Scripts/predict.py m1_7 219 55 
python3 Scripts/predict.py m1_7 211 60 
python3 Scripts/predict.py m1_7 210 65 
